/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bddqvtcmuwivwmxuwbkf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZHF2dGNtdXdpdndteHV3YmtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNDkzMTEsImV4cCI6MjA3NzgyNTMxMX0.-0oJOCw04FVNeDrpsKsUm8iG5SnfRFBmbk78jo-yXPY"