/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as _privateRouteRouteImport } from './routes/__private/route';
import { Route as _privateStudentDashboardIndexRouteImport } from './routes/__private/student/dashboard/index';
import { Route as _privateTutorDashboardIndexRouteImport } from './routes/__private/tutor/dashboard/index';
import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthChangePasswordIndexRouteImport } from './routes/auth/change-password/index';
import { Route as IndexRouteImport } from './routes/index';

const _privateRouteRoute = _privateRouteRouteImport.update({
    id: '/__private',
    getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any);
const AuthChangePasswordIndexRoute = AuthChangePasswordIndexRouteImport.update({
    id: '/auth/change-password/',
    path: '/auth/change-password/',
    getParentRoute: () => rootRouteImport,
} as any);
const _privateTutorDashboardIndexRoute =
    _privateTutorDashboardIndexRouteImport.update({
        id: '/tutor/dashboard/',
        path: '/tutor/dashboard/',
        getParentRoute: () => _privateRouteRoute,
    } as any);
const _privateStudentDashboardIndexRoute =
    _privateStudentDashboardIndexRouteImport.update({
        id: '/student/dashboard/',
        path: '/student/dashboard/',
        getParentRoute: () => _privateRouteRoute,
    } as any);

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute;
    '/auth/change-password': typeof AuthChangePasswordIndexRoute;
    '/student/dashboard': typeof _privateStudentDashboardIndexRoute;
    '/tutor/dashboard': typeof _privateTutorDashboardIndexRoute;
}
export interface FileRoutesByTo {
    '/': typeof IndexRoute;
    '/auth/change-password': typeof AuthChangePasswordIndexRoute;
    '/student/dashboard': typeof _privateStudentDashboardIndexRoute;
    '/tutor/dashboard': typeof _privateTutorDashboardIndexRoute;
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport;
    '/': typeof IndexRoute;
    '/__private': typeof _privateRouteRouteWithChildren;
    '/auth/change-password/': typeof AuthChangePasswordIndexRoute;
    '/__private/student/dashboard/': typeof _privateStudentDashboardIndexRoute;
    '/__private/tutor/dashboard/': typeof _privateTutorDashboardIndexRoute;
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths:
        | '/'
        | '/auth/change-password'
        | '/student/dashboard'
        | '/tutor/dashboard';
    fileRoutesByTo: FileRoutesByTo;
    to:
        | '/'
        | '/auth/change-password'
        | '/student/dashboard'
        | '/tutor/dashboard';
    id:
        | '__root__'
        | '/'
        | '/__private'
        | '/auth/change-password/'
        | '/__private/student/dashboard/'
        | '/__private/tutor/dashboard/';
    fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    _privateRouteRoute: typeof _privateRouteRouteWithChildren;
    AuthChangePasswordIndexRoute: typeof AuthChangePasswordIndexRoute;
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/__private': {
            id: '/__private';
            path: '';
            fullPath: '';
            preLoaderRoute: typeof _privateRouteRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/': {
            id: '/';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof IndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/auth/change-password/': {
            id: '/auth/change-password/';
            path: '/auth/change-password';
            fullPath: '/auth/change-password';
            preLoaderRoute: typeof AuthChangePasswordIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/__private/tutor/dashboard/': {
            id: '/__private/tutor/dashboard/';
            path: '/tutor/dashboard';
            fullPath: '/tutor/dashboard';
            preLoaderRoute: typeof _privateTutorDashboardIndexRouteImport;
            parentRoute: typeof _privateRouteRoute;
        };
        '/__private/student/dashboard/': {
            id: '/__private/student/dashboard/';
            path: '/student/dashboard';
            fullPath: '/student/dashboard';
            preLoaderRoute: typeof _privateStudentDashboardIndexRouteImport;
            parentRoute: typeof _privateRouteRoute;
        };
    }
}

interface _privateRouteRouteChildren {
    _privateStudentDashboardIndexRoute: typeof _privateStudentDashboardIndexRoute;
    _privateTutorDashboardIndexRoute: typeof _privateTutorDashboardIndexRoute;
}

const _privateRouteRouteChildren: _privateRouteRouteChildren = {
    _privateStudentDashboardIndexRoute: _privateStudentDashboardIndexRoute,
    _privateTutorDashboardIndexRoute: _privateTutorDashboardIndexRoute,
};

const _privateRouteRouteWithChildren = _privateRouteRoute._addFileChildren(
    _privateRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    _privateRouteRoute: _privateRouteRouteWithChildren,
    AuthChangePasswordIndexRoute: AuthChangePasswordIndexRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();
