/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as _privateAdminDashboardIndexRouteImport } from './routes/__private/admin/dashboard/index';
import { Route as _privateAdminReportsIndexRouteImport } from './routes/__private/admin/reports/index';
import { Route as _privateAdminSessionsIndexRouteImport } from './routes/__private/admin/sessions/index';
import { Route as _privateAdminSettingsIndexRouteImport } from './routes/__private/admin/settings/index';
import { Route as _privateAdminStudentsIndexRouteImport } from './routes/__private/admin/students/index';
import { Route as _privateAdminTutorsIndexRouteImport } from './routes/__private/admin/tutors/index';
import { Route as _privateCoordinatorIndexRouteImport } from './routes/__private/coordinator/index';
import { Route as _privateCoordinatorRouteRouteImport } from './routes/__private/coordinator/route';
import { Route as _privateRouteRouteImport } from './routes/__private/route';
import { Route as _privateStudentDashboardIndexRouteImport } from './routes/__private/student/dashboard/index';
import { Route as _privateStudentFindTutorIndexRouteImport } from './routes/__private/student/find-tutor/index';
import { Route as _privateStudentMaterialsIndexRouteImport } from './routes/__private/student/materials/index';
import { Route as _privateStudentMySessionsIndexRouteImport } from './routes/__private/student/my-sessions/index';
import { Route as _privateStudentNotificationsIndexRouteImport } from './routes/__private/student/notifications/index';
import { Route as _privateStudentProfileIndexRouteImport } from './routes/__private/student/profile/index';
import { Route as _privateStudentProgressIndexRouteImport } from './routes/__private/student/progress/index';
import { Route as _privateStudentRouteRouteImport } from './routes/__private/student/route';
import { Route as _privateTutorAvailabilityIndexRouteImport } from './routes/__private/tutor/availability/index';
import { Route as _privateTutorDashboardIndexRouteImport } from './routes/__private/tutor/dashboard/index';
import { Route as _privateTutorFeedbackIndexRouteImport } from './routes/__private/tutor/feedback/index';
import { Route as _privateTutorMaterialsIndexRouteImport } from './routes/__private/tutor/materials/index';
import { Route as _privateTutorMyStudentsIndexRouteImport } from './routes/__private/tutor/my-students/index';
import { Route as _privateTutorNotificationsIndexRouteImport } from './routes/__private/tutor/notifications/index';
import { Route as _privateTutorProfileIndexRouteImport } from './routes/__private/tutor/profile/index';
import { Route as _privateTutorRouteRouteImport } from './routes/__private/tutor/route';
import { Route as _privateTutorSessionsIndexRouteImport } from './routes/__private/tutor/sessions/index';
import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthChangePasswordIndexRouteImport } from './routes/auth/change-password/index';
import { Route as IndexRouteImport } from './routes/index';

const _privateRouteRoute = _privateRouteRouteImport.update({
    id: '/__private',
    getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any);
const _privateTutorRouteRoute = _privateTutorRouteRouteImport.update({
    id: '/tutor',
    path: '/tutor',
    getParentRoute: () => _privateRouteRoute,
} as any);
const _privateStudentRouteRoute = _privateStudentRouteRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => _privateRouteRoute,
} as any);
const _privateCoordinatorRouteRoute =
    _privateCoordinatorRouteRouteImport.update({
        id: '/coordinator',
        path: '/coordinator',
        getParentRoute: () => _privateRouteRoute,
    } as any);
const AuthChangePasswordIndexRoute = AuthChangePasswordIndexRouteImport.update({
    id: '/auth/change-password/',
    path: '/auth/change-password/',
    getParentRoute: () => rootRouteImport,
} as any);
const _privateCoordinatorIndexRoute =
    _privateCoordinatorIndexRouteImport.update({
        id: '/',
        path: '/',
        getParentRoute: () => _privateCoordinatorRouteRoute,
    } as any);
const _privateTutorSessionsIndexRoute =
    _privateTutorSessionsIndexRouteImport.update({
        id: '/sessions/',
        path: '/sessions/',
        getParentRoute: () => _privateTutorRouteRoute,
    } as any);
const _privateTutorProfileIndexRoute =
    _privateTutorProfileIndexRouteImport.update({
        id: '/profile/',
        path: '/profile/',
        getParentRoute: () => _privateTutorRouteRoute,
    } as any);
const _privateTutorNotificationsIndexRoute =
    _privateTutorNotificationsIndexRouteImport.update({
        id: '/notifications/',
        path: '/notifications/',
        getParentRoute: () => _privateTutorRouteRoute,
    } as any);
const _privateTutorMyStudentsIndexRoute =
    _privateTutorMyStudentsIndexRouteImport.update({
        id: '/my-students/',
        path: '/my-students/',
        getParentRoute: () => _privateTutorRouteRoute,
    } as any);
const _privateTutorMaterialsIndexRoute =
    _privateTutorMaterialsIndexRouteImport.update({
        id: '/materials/',
        path: '/materials/',
        getParentRoute: () => _privateTutorRouteRoute,
    } as any);
const _privateTutorFeedbackIndexRoute =
    _privateTutorFeedbackIndexRouteImport.update({
        id: '/feedback/',
        path: '/feedback/',
        getParentRoute: () => _privateTutorRouteRoute,
    } as any);
const _privateTutorDashboardIndexRoute =
    _privateTutorDashboardIndexRouteImport.update({
        id: '/dashboard/',
        path: '/dashboard/',
        getParentRoute: () => _privateTutorRouteRoute,
    } as any);
const _privateTutorAvailabilityIndexRoute =
    _privateTutorAvailabilityIndexRouteImport.update({
        id: '/availability/',
        path: '/availability/',
        getParentRoute: () => _privateTutorRouteRoute,
    } as any);
const _privateStudentProgressIndexRoute =
    _privateStudentProgressIndexRouteImport.update({
        id: '/progress/',
        path: '/progress/',
        getParentRoute: () => _privateStudentRouteRoute,
    } as any);
const _privateStudentProfileIndexRoute =
    _privateStudentProfileIndexRouteImport.update({
        id: '/profile/',
        path: '/profile/',
        getParentRoute: () => _privateStudentRouteRoute,
    } as any);
const _privateStudentNotificationsIndexRoute =
    _privateStudentNotificationsIndexRouteImport.update({
        id: '/notifications/',
        path: '/notifications/',
        getParentRoute: () => _privateStudentRouteRoute,
    } as any);
const _privateStudentMySessionsIndexRoute =
    _privateStudentMySessionsIndexRouteImport.update({
        id: '/my-sessions/',
        path: '/my-sessions/',
        getParentRoute: () => _privateStudentRouteRoute,
    } as any);
const _privateStudentMaterialsIndexRoute =
    _privateStudentMaterialsIndexRouteImport.update({
        id: '/materials/',
        path: '/materials/',
        getParentRoute: () => _privateStudentRouteRoute,
    } as any);
const _privateStudentFindTutorIndexRoute =
    _privateStudentFindTutorIndexRouteImport.update({
        id: '/find-tutor/',
        path: '/find-tutor/',
        getParentRoute: () => _privateStudentRouteRoute,
    } as any);
const _privateStudentDashboardIndexRoute =
    _privateStudentDashboardIndexRouteImport.update({
        id: '/dashboard/',
        path: '/dashboard/',
        getParentRoute: () => _privateStudentRouteRoute,
    } as any);
const _privateAdminTutorsIndexRoute =
    _privateAdminTutorsIndexRouteImport.update({
        id: '/admin/tutors/',
        path: '/admin/tutors/',
        getParentRoute: () => _privateRouteRoute,
    } as any);
const _privateAdminStudentsIndexRoute =
    _privateAdminStudentsIndexRouteImport.update({
        id: '/admin/students/',
        path: '/admin/students/',
        getParentRoute: () => _privateRouteRoute,
    } as any);
const _privateAdminSettingsIndexRoute =
    _privateAdminSettingsIndexRouteImport.update({
        id: '/admin/settings/',
        path: '/admin/settings/',
        getParentRoute: () => _privateRouteRoute,
    } as any);
const _privateAdminSessionsIndexRoute =
    _privateAdminSessionsIndexRouteImport.update({
        id: '/admin/sessions/',
        path: '/admin/sessions/',
        getParentRoute: () => _privateRouteRoute,
    } as any);
const _privateAdminReportsIndexRoute =
    _privateAdminReportsIndexRouteImport.update({
        id: '/admin/reports/',
        path: '/admin/reports/',
        getParentRoute: () => _privateRouteRoute,
    } as any);
const _privateAdminDashboardIndexRoute =
    _privateAdminDashboardIndexRouteImport.update({
        id: '/admin/dashboard/',
        path: '/admin/dashboard/',
        getParentRoute: () => _privateRouteRoute,
    } as any);

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute;
    '/coordinator': typeof _privateCoordinatorRouteRouteWithChildren;
    '/student': typeof _privateStudentRouteRouteWithChildren;
    '/tutor': typeof _privateTutorRouteRouteWithChildren;
    '/coordinator/': typeof _privateCoordinatorIndexRoute;
    '/auth/change-password': typeof AuthChangePasswordIndexRoute;
    '/admin/dashboard': typeof _privateAdminDashboardIndexRoute;
    '/admin/reports': typeof _privateAdminReportsIndexRoute;
    '/admin/sessions': typeof _privateAdminSessionsIndexRoute;
    '/admin/settings': typeof _privateAdminSettingsIndexRoute;
    '/admin/students': typeof _privateAdminStudentsIndexRoute;
    '/admin/tutors': typeof _privateAdminTutorsIndexRoute;
    '/student/dashboard': typeof _privateStudentDashboardIndexRoute;
    '/student/find-tutor': typeof _privateStudentFindTutorIndexRoute;
    '/student/materials': typeof _privateStudentMaterialsIndexRoute;
    '/student/my-sessions': typeof _privateStudentMySessionsIndexRoute;
    '/student/notifications': typeof _privateStudentNotificationsIndexRoute;
    '/student/profile': typeof _privateStudentProfileIndexRoute;
    '/student/progress': typeof _privateStudentProgressIndexRoute;
    '/tutor/availability': typeof _privateTutorAvailabilityIndexRoute;
    '/tutor/dashboard': typeof _privateTutorDashboardIndexRoute;
    '/tutor/feedback': typeof _privateTutorFeedbackIndexRoute;
    '/tutor/materials': typeof _privateTutorMaterialsIndexRoute;
    '/tutor/my-students': typeof _privateTutorMyStudentsIndexRoute;
    '/tutor/notifications': typeof _privateTutorNotificationsIndexRoute;
    '/tutor/profile': typeof _privateTutorProfileIndexRoute;
    '/tutor/sessions': typeof _privateTutorSessionsIndexRoute;
}
export interface FileRoutesByTo {
    '/': typeof IndexRoute;
    '/student': typeof _privateStudentRouteRouteWithChildren;
    '/tutor': typeof _privateTutorRouteRouteWithChildren;
    '/coordinator': typeof _privateCoordinatorIndexRoute;
    '/auth/change-password': typeof AuthChangePasswordIndexRoute;
    '/admin/dashboard': typeof _privateAdminDashboardIndexRoute;
    '/admin/reports': typeof _privateAdminReportsIndexRoute;
    '/admin/sessions': typeof _privateAdminSessionsIndexRoute;
    '/admin/settings': typeof _privateAdminSettingsIndexRoute;
    '/admin/students': typeof _privateAdminStudentsIndexRoute;
    '/admin/tutors': typeof _privateAdminTutorsIndexRoute;
    '/student/dashboard': typeof _privateStudentDashboardIndexRoute;
    '/student/find-tutor': typeof _privateStudentFindTutorIndexRoute;
    '/student/materials': typeof _privateStudentMaterialsIndexRoute;
    '/student/my-sessions': typeof _privateStudentMySessionsIndexRoute;
    '/student/notifications': typeof _privateStudentNotificationsIndexRoute;
    '/student/profile': typeof _privateStudentProfileIndexRoute;
    '/student/progress': typeof _privateStudentProgressIndexRoute;
    '/tutor/availability': typeof _privateTutorAvailabilityIndexRoute;
    '/tutor/dashboard': typeof _privateTutorDashboardIndexRoute;
    '/tutor/feedback': typeof _privateTutorFeedbackIndexRoute;
    '/tutor/materials': typeof _privateTutorMaterialsIndexRoute;
    '/tutor/my-students': typeof _privateTutorMyStudentsIndexRoute;
    '/tutor/notifications': typeof _privateTutorNotificationsIndexRoute;
    '/tutor/profile': typeof _privateTutorProfileIndexRoute;
    '/tutor/sessions': typeof _privateTutorSessionsIndexRoute;
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport;
    '/': typeof IndexRoute;
    '/__private': typeof _privateRouteRouteWithChildren;
    '/__private/coordinator': typeof _privateCoordinatorRouteRouteWithChildren;
    '/__private/student': typeof _privateStudentRouteRouteWithChildren;
    '/__private/tutor': typeof _privateTutorRouteRouteWithChildren;
    '/__private/coordinator/': typeof _privateCoordinatorIndexRoute;
    '/auth/change-password/': typeof AuthChangePasswordIndexRoute;
    '/__private/admin/dashboard/': typeof _privateAdminDashboardIndexRoute;
    '/__private/admin/reports/': typeof _privateAdminReportsIndexRoute;
    '/__private/admin/sessions/': typeof _privateAdminSessionsIndexRoute;
    '/__private/admin/settings/': typeof _privateAdminSettingsIndexRoute;
    '/__private/admin/students/': typeof _privateAdminStudentsIndexRoute;
    '/__private/admin/tutors/': typeof _privateAdminTutorsIndexRoute;
    '/__private/student/dashboard/': typeof _privateStudentDashboardIndexRoute;
    '/__private/student/find-tutor/': typeof _privateStudentFindTutorIndexRoute;
    '/__private/student/materials/': typeof _privateStudentMaterialsIndexRoute;
    '/__private/student/my-sessions/': typeof _privateStudentMySessionsIndexRoute;
    '/__private/student/notifications/': typeof _privateStudentNotificationsIndexRoute;
    '/__private/student/profile/': typeof _privateStudentProfileIndexRoute;
    '/__private/student/progress/': typeof _privateStudentProgressIndexRoute;
    '/__private/tutor/availability/': typeof _privateTutorAvailabilityIndexRoute;
    '/__private/tutor/dashboard/': typeof _privateTutorDashboardIndexRoute;
    '/__private/tutor/feedback/': typeof _privateTutorFeedbackIndexRoute;
    '/__private/tutor/materials/': typeof _privateTutorMaterialsIndexRoute;
    '/__private/tutor/my-students/': typeof _privateTutorMyStudentsIndexRoute;
    '/__private/tutor/notifications/': typeof _privateTutorNotificationsIndexRoute;
    '/__private/tutor/profile/': typeof _privateTutorProfileIndexRoute;
    '/__private/tutor/sessions/': typeof _privateTutorSessionsIndexRoute;
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths:
        | '/'
        | '/coordinator'
        | '/student'
        | '/tutor'
        | '/coordinator/'
        | '/auth/change-password'
        | '/admin/dashboard'
        | '/admin/reports'
        | '/admin/sessions'
        | '/admin/settings'
        | '/admin/students'
        | '/admin/tutors'
        | '/student/dashboard'
        | '/student/find-tutor'
        | '/student/materials'
        | '/student/my-sessions'
        | '/student/notifications'
        | '/student/profile'
        | '/student/progress'
        | '/tutor/availability'
        | '/tutor/dashboard'
        | '/tutor/feedback'
        | '/tutor/materials'
        | '/tutor/my-students'
        | '/tutor/notifications'
        | '/tutor/profile'
        | '/tutor/sessions';
    fileRoutesByTo: FileRoutesByTo;
    to:
        | '/'
        | '/student'
        | '/tutor'
        | '/coordinator'
        | '/auth/change-password'
        | '/admin/dashboard'
        | '/admin/reports'
        | '/admin/sessions'
        | '/admin/settings'
        | '/admin/students'
        | '/admin/tutors'
        | '/student/dashboard'
        | '/student/find-tutor'
        | '/student/materials'
        | '/student/my-sessions'
        | '/student/notifications'
        | '/student/profile'
        | '/student/progress'
        | '/tutor/availability'
        | '/tutor/dashboard'
        | '/tutor/feedback'
        | '/tutor/materials'
        | '/tutor/my-students'
        | '/tutor/notifications'
        | '/tutor/profile'
        | '/tutor/sessions';
    id:
        | '__root__'
        | '/'
        | '/__private'
        | '/__private/coordinator'
        | '/__private/student'
        | '/__private/tutor'
        | '/__private/coordinator/'
        | '/auth/change-password/'
        | '/__private/admin/dashboard/'
        | '/__private/admin/reports/'
        | '/__private/admin/sessions/'
        | '/__private/admin/settings/'
        | '/__private/admin/students/'
        | '/__private/admin/tutors/'
        | '/__private/student/dashboard/'
        | '/__private/student/find-tutor/'
        | '/__private/student/materials/'
        | '/__private/student/my-sessions/'
        | '/__private/student/notifications/'
        | '/__private/student/profile/'
        | '/__private/student/progress/'
        | '/__private/tutor/availability/'
        | '/__private/tutor/dashboard/'
        | '/__private/tutor/feedback/'
        | '/__private/tutor/materials/'
        | '/__private/tutor/my-students/'
        | '/__private/tutor/notifications/'
        | '/__private/tutor/profile/'
        | '/__private/tutor/sessions/';
    fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    _privateRouteRoute: typeof _privateRouteRouteWithChildren;
    AuthChangePasswordIndexRoute: typeof AuthChangePasswordIndexRoute;
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/__private': {
            id: '/__private';
            path: '';
            fullPath: '';
            preLoaderRoute: typeof _privateRouteRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/': {
            id: '/';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof IndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/__private/tutor': {
            id: '/__private/tutor';
            path: '/tutor';
            fullPath: '/tutor';
            preLoaderRoute: typeof _privateTutorRouteRouteImport;
            parentRoute: typeof _privateRouteRoute;
        };
        '/__private/student': {
            id: '/__private/student';
            path: '/student';
            fullPath: '/student';
            preLoaderRoute: typeof _privateStudentRouteRouteImport;
            parentRoute: typeof _privateRouteRoute;
        };
        '/__private/coordinator': {
            id: '/__private/coordinator';
            path: '/coordinator';
            fullPath: '/coordinator';
            preLoaderRoute: typeof _privateCoordinatorRouteRouteImport;
            parentRoute: typeof _privateRouteRoute;
        };
        '/auth/change-password/': {
            id: '/auth/change-password/';
            path: '/auth/change-password';
            fullPath: '/auth/change-password';
            preLoaderRoute: typeof AuthChangePasswordIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/__private/coordinator/': {
            id: '/__private/coordinator/';
            path: '/';
            fullPath: '/coordinator/';
            preLoaderRoute: typeof _privateCoordinatorIndexRouteImport;
            parentRoute: typeof _privateCoordinatorRouteRoute;
        };
        '/__private/tutor/sessions/': {
            id: '/__private/tutor/sessions/';
            path: '/sessions';
            fullPath: '/tutor/sessions';
            preLoaderRoute: typeof _privateTutorSessionsIndexRouteImport;
            parentRoute: typeof _privateTutorRouteRoute;
        };
        '/__private/tutor/profile/': {
            id: '/__private/tutor/profile/';
            path: '/profile';
            fullPath: '/tutor/profile';
            preLoaderRoute: typeof _privateTutorProfileIndexRouteImport;
            parentRoute: typeof _privateTutorRouteRoute;
        };
        '/__private/tutor/notifications/': {
            id: '/__private/tutor/notifications/';
            path: '/notifications';
            fullPath: '/tutor/notifications';
            preLoaderRoute: typeof _privateTutorNotificationsIndexRouteImport;
            parentRoute: typeof _privateTutorRouteRoute;
        };
        '/__private/tutor/my-students/': {
            id: '/__private/tutor/my-students/';
            path: '/my-students';
            fullPath: '/tutor/my-students';
            preLoaderRoute: typeof _privateTutorMyStudentsIndexRouteImport;
            parentRoute: typeof _privateTutorRouteRoute;
        };
        '/__private/tutor/materials/': {
            id: '/__private/tutor/materials/';
            path: '/materials';
            fullPath: '/tutor/materials';
            preLoaderRoute: typeof _privateTutorMaterialsIndexRouteImport;
            parentRoute: typeof _privateTutorRouteRoute;
        };
        '/__private/tutor/feedback/': {
            id: '/__private/tutor/feedback/';
            path: '/feedback';
            fullPath: '/tutor/feedback';
            preLoaderRoute: typeof _privateTutorFeedbackIndexRouteImport;
            parentRoute: typeof _privateTutorRouteRoute;
        };
        '/__private/tutor/dashboard/': {
            id: '/__private/tutor/dashboard/';
            path: '/dashboard';
            fullPath: '/tutor/dashboard';
            preLoaderRoute: typeof _privateTutorDashboardIndexRouteImport;
            parentRoute: typeof _privateTutorRouteRoute;
        };
        '/__private/tutor/availability/': {
            id: '/__private/tutor/availability/';
            path: '/availability';
            fullPath: '/tutor/availability';
            preLoaderRoute: typeof _privateTutorAvailabilityIndexRouteImport;
            parentRoute: typeof _privateTutorRouteRoute;
        };
        '/__private/student/progress/': {
            id: '/__private/student/progress/';
            path: '/progress';
            fullPath: '/student/progress';
            preLoaderRoute: typeof _privateStudentProgressIndexRouteImport;
            parentRoute: typeof _privateStudentRouteRoute;
        };
        '/__private/student/profile/': {
            id: '/__private/student/profile/';
            path: '/profile';
            fullPath: '/student/profile';
            preLoaderRoute: typeof _privateStudentProfileIndexRouteImport;
            parentRoute: typeof _privateStudentRouteRoute;
        };
        '/__private/student/notifications/': {
            id: '/__private/student/notifications/';
            path: '/notifications';
            fullPath: '/student/notifications';
            preLoaderRoute: typeof _privateStudentNotificationsIndexRouteImport;
            parentRoute: typeof _privateStudentRouteRoute;
        };
        '/__private/student/my-sessions/': {
            id: '/__private/student/my-sessions/';
            path: '/my-sessions';
            fullPath: '/student/my-sessions';
            preLoaderRoute: typeof _privateStudentMySessionsIndexRouteImport;
            parentRoute: typeof _privateStudentRouteRoute;
        };
        '/__private/student/materials/': {
            id: '/__private/student/materials/';
            path: '/materials';
            fullPath: '/student/materials';
            preLoaderRoute: typeof _privateStudentMaterialsIndexRouteImport;
            parentRoute: typeof _privateStudentRouteRoute;
        };
        '/__private/student/find-tutor/': {
            id: '/__private/student/find-tutor/';
            path: '/find-tutor';
            fullPath: '/student/find-tutor';
            preLoaderRoute: typeof _privateStudentFindTutorIndexRouteImport;
            parentRoute: typeof _privateStudentRouteRoute;
        };
        '/__private/student/dashboard/': {
            id: '/__private/student/dashboard/';
            path: '/dashboard';
            fullPath: '/student/dashboard';
            preLoaderRoute: typeof _privateStudentDashboardIndexRouteImport;
            parentRoute: typeof _privateStudentRouteRoute;
        };
        '/__private/admin/tutors/': {
            id: '/__private/admin/tutors/';
            path: '/admin/tutors';
            fullPath: '/admin/tutors';
            preLoaderRoute: typeof _privateAdminTutorsIndexRouteImport;
            parentRoute: typeof _privateRouteRoute;
        };
        '/__private/admin/students/': {
            id: '/__private/admin/students/';
            path: '/admin/students';
            fullPath: '/admin/students';
            preLoaderRoute: typeof _privateAdminStudentsIndexRouteImport;
            parentRoute: typeof _privateRouteRoute;
        };
        '/__private/admin/settings/': {
            id: '/__private/admin/settings/';
            path: '/admin/settings';
            fullPath: '/admin/settings';
            preLoaderRoute: typeof _privateAdminSettingsIndexRouteImport;
            parentRoute: typeof _privateRouteRoute;
        };
        '/__private/admin/sessions/': {
            id: '/__private/admin/sessions/';
            path: '/admin/sessions';
            fullPath: '/admin/sessions';
            preLoaderRoute: typeof _privateAdminSessionsIndexRouteImport;
            parentRoute: typeof _privateRouteRoute;
        };
        '/__private/admin/reports/': {
            id: '/__private/admin/reports/';
            path: '/admin/reports';
            fullPath: '/admin/reports';
            preLoaderRoute: typeof _privateAdminReportsIndexRouteImport;
            parentRoute: typeof _privateRouteRoute;
        };
        '/__private/admin/dashboard/': {
            id: '/__private/admin/dashboard/';
            path: '/admin/dashboard';
            fullPath: '/admin/dashboard';
            preLoaderRoute: typeof _privateAdminDashboardIndexRouteImport;
            parentRoute: typeof _privateRouteRoute;
        };
    }
}

interface _privateCoordinatorRouteRouteChildren {
    _privateCoordinatorIndexRoute: typeof _privateCoordinatorIndexRoute;
}

const _privateCoordinatorRouteRouteChildren: _privateCoordinatorRouteRouteChildren =
    {
        _privateCoordinatorIndexRoute: _privateCoordinatorIndexRoute,
    };

const _privateCoordinatorRouteRouteWithChildren =
    _privateCoordinatorRouteRoute._addFileChildren(
        _privateCoordinatorRouteRouteChildren,
    );

interface _privateStudentRouteRouteChildren {
    _privateStudentDashboardIndexRoute: typeof _privateStudentDashboardIndexRoute;
    _privateStudentFindTutorIndexRoute: typeof _privateStudentFindTutorIndexRoute;
    _privateStudentMaterialsIndexRoute: typeof _privateStudentMaterialsIndexRoute;
    _privateStudentMySessionsIndexRoute: typeof _privateStudentMySessionsIndexRoute;
    _privateStudentNotificationsIndexRoute: typeof _privateStudentNotificationsIndexRoute;
    _privateStudentProfileIndexRoute: typeof _privateStudentProfileIndexRoute;
    _privateStudentProgressIndexRoute: typeof _privateStudentProgressIndexRoute;
}

const _privateStudentRouteRouteChildren: _privateStudentRouteRouteChildren = {
    _privateStudentDashboardIndexRoute: _privateStudentDashboardIndexRoute,
    _privateStudentFindTutorIndexRoute: _privateStudentFindTutorIndexRoute,
    _privateStudentMaterialsIndexRoute: _privateStudentMaterialsIndexRoute,
    _privateStudentMySessionsIndexRoute: _privateStudentMySessionsIndexRoute,
    _privateStudentNotificationsIndexRoute:
        _privateStudentNotificationsIndexRoute,
    _privateStudentProfileIndexRoute: _privateStudentProfileIndexRoute,
    _privateStudentProgressIndexRoute: _privateStudentProgressIndexRoute,
};

const _privateStudentRouteRouteWithChildren =
    _privateStudentRouteRoute._addFileChildren(
        _privateStudentRouteRouteChildren,
    );

interface _privateTutorRouteRouteChildren {
    _privateTutorAvailabilityIndexRoute: typeof _privateTutorAvailabilityIndexRoute;
    _privateTutorDashboardIndexRoute: typeof _privateTutorDashboardIndexRoute;
    _privateTutorFeedbackIndexRoute: typeof _privateTutorFeedbackIndexRoute;
    _privateTutorMaterialsIndexRoute: typeof _privateTutorMaterialsIndexRoute;
    _privateTutorMyStudentsIndexRoute: typeof _privateTutorMyStudentsIndexRoute;
    _privateTutorNotificationsIndexRoute: typeof _privateTutorNotificationsIndexRoute;
    _privateTutorProfileIndexRoute: typeof _privateTutorProfileIndexRoute;
    _privateTutorSessionsIndexRoute: typeof _privateTutorSessionsIndexRoute;
}

const _privateTutorRouteRouteChildren: _privateTutorRouteRouteChildren = {
    _privateTutorAvailabilityIndexRoute: _privateTutorAvailabilityIndexRoute,
    _privateTutorDashboardIndexRoute: _privateTutorDashboardIndexRoute,
    _privateTutorFeedbackIndexRoute: _privateTutorFeedbackIndexRoute,
    _privateTutorMaterialsIndexRoute: _privateTutorMaterialsIndexRoute,
    _privateTutorMyStudentsIndexRoute: _privateTutorMyStudentsIndexRoute,
    _privateTutorNotificationsIndexRoute: _privateTutorNotificationsIndexRoute,
    _privateTutorProfileIndexRoute: _privateTutorProfileIndexRoute,
    _privateTutorSessionsIndexRoute: _privateTutorSessionsIndexRoute,
};

const _privateTutorRouteRouteWithChildren =
    _privateTutorRouteRoute._addFileChildren(_privateTutorRouteRouteChildren);

interface _privateRouteRouteChildren {
    _privateCoordinatorRouteRoute: typeof _privateCoordinatorRouteRouteWithChildren;
    _privateStudentRouteRoute: typeof _privateStudentRouteRouteWithChildren;
    _privateTutorRouteRoute: typeof _privateTutorRouteRouteWithChildren;
    _privateAdminDashboardIndexRoute: typeof _privateAdminDashboardIndexRoute;
    _privateAdminReportsIndexRoute: typeof _privateAdminReportsIndexRoute;
    _privateAdminSessionsIndexRoute: typeof _privateAdminSessionsIndexRoute;
    _privateAdminSettingsIndexRoute: typeof _privateAdminSettingsIndexRoute;
    _privateAdminStudentsIndexRoute: typeof _privateAdminStudentsIndexRoute;
    _privateAdminTutorsIndexRoute: typeof _privateAdminTutorsIndexRoute;
}

const _privateRouteRouteChildren: _privateRouteRouteChildren = {
    _privateCoordinatorRouteRoute: _privateCoordinatorRouteRouteWithChildren,
    _privateStudentRouteRoute: _privateStudentRouteRouteWithChildren,
    _privateTutorRouteRoute: _privateTutorRouteRouteWithChildren,
    _privateAdminDashboardIndexRoute: _privateAdminDashboardIndexRoute,
    _privateAdminReportsIndexRoute: _privateAdminReportsIndexRoute,
    _privateAdminSessionsIndexRoute: _privateAdminSessionsIndexRoute,
    _privateAdminSettingsIndexRoute: _privateAdminSettingsIndexRoute,
    _privateAdminStudentsIndexRoute: _privateAdminStudentsIndexRoute,
    _privateAdminTutorsIndexRoute: _privateAdminTutorsIndexRoute,
};

const _privateRouteRouteWithChildren = _privateRouteRoute._addFileChildren(
    _privateRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    _privateRouteRoute: _privateRouteRouteWithChildren,
    AuthChangePasswordIndexRoute: AuthChangePasswordIndexRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();
